repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.1
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==24.3.0
